replicaCount: 1

image:
  repository: gcr.io/wr-code-test/test
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - rlt-test.rivera.engineer
  tls: []


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
